---
host:          'https://beta-moses.energytransitionmodel.com'
etengine_host: 'https://beta-engine.energytransitionmodel.com'
etmodel_host:  'https://beta-pro.energytransitionmodel.com'

# Path to static files loaded by ActiveHash.
static_data_path: 'db/static'

cache:
  # Cache the results of network calculations.
  networks: true
